### ISSUE TITLE
L.imageOverlay.Canvas

### ISSUE THREAD

**Issue by kwankong** [GIAPspzoo/L.TileLayer.Canvas#17]
Hi, GIAPspzoo.  I load many layers using ImageOverlay in my projects and I get performance issues when the images are large.  I was thinking that somehow I can just capture what appears on the Leaflet window instead of operating on the entire image.  So I would like to try your method on ImageOverlay but not exactly sure how to go about doing that yet.

**Comment by marlo22** [comment]
Hi @kwankong :slightly_smiling_face: 

Currently, `L.TileLayer.Canvas` is an extension of the `L.TileLayer` class - it doesn't support `L.ImageOverlay`.

You can try to prepare an extension for `L.ImageOverlay` by yourself, I suppose it'll work similair as for `L.TileLayer`. If you need you can look at the source code of our plugin and try to apply this logic to your own implementation for `L.ImageOverlay`.

If you have questions, please feel free to ask.

**Comment by kwankong** [comment]
Thanks, GIAPspzoo.  This would be my first attempt to write an extension, and so I'll likely need more help along the way.  Taking a look at your codes, what are the purposes of (a) doubleSize, (b) delaysForZoom?

**Comment by marlo22** [comment]
When it comes to `doubleSize`,  it's a parameter for using bigger tiles (2x) for high-resolution displays (e.g. Retina).

I'm not 100% sure about delaysForZoom (because it was a few years ago), but if I'm correct we had an issue with blinking tiles on zoom change and timeout was a bypass to omit this problem.

I suggest to start from the simplest possible implementation and not worry too much about more advanced features at the beginning. :wink:

**Comment by marlo22** [comment]
Closed due to inactivity.
